name: Publish package to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and publish to OSSRH
        run: |
          mvn -B -U \
            -Pci-cd \
            release:prepare \
            release:perform \
            javadoc:jar \
            source:jar \
            -DskipTests \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            -DossrhUsername=${{ secrets.OSSRH_USERNAME }} \
            -DossrhPassword=${{ secrets.OSSRH_PASSWORD }}
            deploy
        env:
          GPG_EXECUTABLE: gpg
